### ISSUE TITLE
Change permission status colors

### ISSUE THREAD

**Issue by d4rken** [d4rken/mystic-permissions#9]
1. I think the yellow colour is NOT very intuitive. Grey colour would be better in my opinion (including on the permissions screen).

![IMG_20220717_080037](https://user-images.githubusercontent.com/54448474/179381569-d74ed2ee-cffa-44da-af94-5ff12d00b2e0.jpg)

_Originally posted by @TheMysticS in https://github.com/d4rken/mystic-permissions/issues/1#issuecomment-1186378156_

**Comment by TheMysticS** [comment]
Please replace colour of permissions denied from White to Grey. 

![Screenshot_2022-07-17-19-54-54-17_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179402964-8569094d-7e5d-4998-9c35-80e6c8d0abbc.jpg)

**Comment by d4rken** [comment]
Adjusted in 004284854e8f20b79dd2c9eaa0b0fc3f52b37398

**Comment by TheMysticS** [comment]
While in dark mode, it is kind of okay (dark grey), it is (almost) black in light mode. Can you adjust it to be light grey in both modes?

#ECECEC or #DEDEDE or #D4D4D4?

[Screenshot_2022-07-18-08-15-15-67_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/54448474/179438543-2a733be2-bd3c-4152-9ab1-82962f3a7268.jpg)

The idea is it should communicate the fact that a permission is 'disabled' or 'turned OFF'.

**Comment by TheMysticS** [comment]
Unable to add image in comments during edit. 

Dark Mode:

[Screenshot_2022-07-18-08-25-16-30_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/54448474/179438946-effba0a0-ba8d-4c53-9de6-cea277621991.jpg)

**Comment by TheMysticS** [comment]
At the moment, these don't look that good:

[Screenshot_2022-07-18-08-28-15-02_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179439225-b7a5068c-edfb-495e-aab6-272fc9d0ad33.jpg)


[Screenshot_2022-07-18-08-28-34-00_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179439235-400d3dbb-fe48-4150-8f94-ed820c6e7029.jpg)

**Comment by TheMysticS** [comment]
The grey icons look great now. Thank you.

However, can you revert to the light orange colour that you used earlier for the permission status?

[Screenshot](https://user-images.githubusercontent.com/54448474/179673097-de202fc1-0ddc-46c8-a6d6-ad7138a476bf.jpg)

**Comment by d4rken** [comment]
Hm isn't it confusing if we use two different colors for the same state?

I also like that it's no longer a "bad" or "good" color. Mystic Perm should not judge whether it is bad or good that permission are granted.

**Comment by TheMysticS** [comment]
> Hm isn't it confusing if we use two different colors for the same state?
> 
That's what I wanted to avoid earlier. But at that time, I had not seen how it would actually look like in the app. 

In v.0.2.4, the permissions page isn't using the grey colour that has been implemented in the Apps tab. It is using Black in light theme and white in dark theme, which looks awkward. Cam you change those to the same grey colour and see how it looks? The choice of colours must be such that it looks good in both themes (light and dark), as well as communicates the message intended very intuitively.

> I also like that it's no longer a "bad" or "good" color. Mystic Perm should not judge whether it is bad or good that permission are granted.
>
It never was meant to be that way. A green colour signifies an allowed permission, not good or bad. Likewise, the orange colour doesn't signify anything bad. It's just that on the Apps tab, it could have been confusing since there are no markers inside (the tick mark inside green circle or the hyphen inside the orange circle).

You are not using these markers in the Apps tab, so it was suggested that you make them look like the System Quick Settings, where enabled toggles are in colour, while the disabled ones are greyed out. Nothing again with anything being good or bad.
